# Generated by Django 5.1.6 on 2025-04-14 02:28

import merkachecheres.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merkachecheres', '0017_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/perfiles', validators=[merkachecheres.models.validar_extension_imagen], verbose_name='Ruta de la imagen de perfil'),
        ),
    ]
