# Generated by Django 5.1.1 on 2025-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merkachecheres', '0019_producto_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Electrónica'), (2, 'Ropa y Accesorios'), (3, 'Hogar y Jardín'), (4, 'Ferretería'), (5, 'Libros y Papelería'), (6, 'Belleza y Cuidado Personal'), (7, 'Juguetes'), (8, 'Deporte'), (9, 'Vehículos')], default=0),
        ),
    ]
