# Generated by Django 5.1.1 on 2025-07-15 20:36

import merkachecheres.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merkachecheres', '0025_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='usuarios/perfiles/user_default.jpg', null=True, upload_to='usuarios/perfiles', validators=[merkachecheres.models.validar_extension_imagen], verbose_name='Ruta de la imagen de perfil'),
        ),
    ]
