# Generated by Django 5.1.6 on 2025-08-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merkachecheres', '0028_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
